spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mission-checker
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
